import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react';
import axios from "axios";
import "bootstrap/dist/css/bootstrap.min.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import Solicitudes from '../components/Solicitudes'

export default function Home(solicitud) {
  return (
    <div className={styles.container}>
      <Head>
        <title>SISCON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/SISCON.png" />
      </Head>

      <main className={styles.main}>
        <Image  src="/SISCON.png" width="360" height="80.7" />
        <h1 className={styles.title}>
          Seguimiento de solicitud de prótesis
        </h1>
      </main>

<div className={styles.search}>
      <div className="App">
        <div className="containerInput">
          <input
            className="form-control inputBuscar"
           // value={busqueda}
            placeholder="Búsqueda por Nombre, DNI o Número de afiliado"
          //  onChange={handleChange}
          />
          <button className="btn btn-success">
          
        </button>
        </div>



        <div className="table-responsive">
          <table className="table table-sm table-bordered">
            <thead className={styles.table}>
              <tr>
                <th>Nombre y Apellido</th>
                <th>Documento</th>
                <th>Localidad</th>
                <th>Nro de afiliado</th>
                <th>Sexo</th>
                <th>Medico</th>
                <th>Clinica</th>
                <th>Estado de paciente</th>
                <th>Estado de solicitud</th>
                </tr>
            </thead>


          </table>  

        </div>


</div>
</div>

     //*  <div> <Solicitudes/> </div>

      </div>
  )
}


/**
export const getServerSideProps = async(context) =>{
  const rest = await fetch("http://siscon.info/api/sol_entrantes")
  const solicitudes = await rest.json()
  return{
    props:{
      solicitud : solicitudes
    }
  }



}*/


